### ISSUE TITLE
test suite cannot be run offline

### ISSUE THREAD

**Issue by Apteryks** [ruby/net-imap#136]
Hi,

When attempting to run the test suite with `rake test`, it appears to attempt reaching to the network to fetch RFCs:

```
starting phase `check'
rake aborted!
SocketError: Failed to open TCP connection to www.rfc-editor.org:443 (getaddrinfo: Name or service not known)
/gnu/store/2y2hkxzygxqcxy4mzdfkw50j6s88jjw7-ruby-timeout-0.3.2/lib/ruby/vendor_ruby/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
/gnu/store/2y2hkxzygxqcxy4mzdfkw50j6s88jjw7-ruby-timeout-0.3.2/lib/ruby/vendor_ruby/gems/timeout-0.3.2/lib/timeout.rb:196:in `timeout'
/tmp/guix-build-ruby-net-imap-0.3.4.drv-0/source/rakelib/rfcs.rake:164:in `block in <top (required)>'

Caused by:
SocketError: getaddrinfo: Name or service not known
/gnu/store/2y2hkxzygxqcxy4mzdfkw50j6s88jjw7-ruby-timeout-0.3.2/lib/ruby/vendor_ruby/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
/gnu/store/2y2hkxzygxqcxy4mzdfkw50j6s88jjw7-ruby-timeout-0.3.2/lib/ruby/vendor_ruby/gems/timeout-0.3.2/lib/timeout.rb:196:in `timeout'
/tmp/guix-build-ruby-net-imap-0.3.4.drv-0/source/rakelib/rfcs.rake:164:in `block in <top (required)>'
Tasks: TOP => test => saslprep_rb => lib/net/imap/sasl/stringprep_tables.rb => rfcs/rfc3454-stringprep_tables.json => rfcs/rfc3454.txt
(See full trace by running task with --trace)
error: in phase 'check': uncaught exception:

```

It'd be nice if this was not needed and the test suite could be run in an isolated environment.

Thanks!

**Comment by nevans** [comment]
@Apteryks how does #137 look to you?

**Comment by Apteryks** [comment]
Works for me!  See: https://github.com/ruby/net-imap/pull/137#issuecomment-1465089829.
