### ISSUE TITLE
NOOP untagged response sent by Zimbra

### ISSUE THREAD

**Issue by c-leroy** [ruby/net-imap#2]
Hello,

I quite often encounter a response parsing error while issuing long running requests to our Zimbra server :
```
Traceback (most recent call last):
	8: from .rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:1120:in `block in initialize'
	7: from .rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:1147:in `receive_responses'
	6: from .rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:1244:in `get_response'
	5: from .rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:2181:in `parse'
	4: from .rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:2255:in `response'
	3: from .rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:2308:in `response_untagged'
	2: from .rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:2879:in `text_response'
	1: from .rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:3347:in `match'
.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:3495:in `parse_error': unexpected token CRLF (expected SPACE) (Net::IMAP::ResponseParseError)
```
The last time, the server sent a untagged response "* NOOP" while a `close` request was in progress, after I had flagged lots of mails as Deleted :
```
[...]
C: RUBY0037 UID STORE 3668787,3668788,3668790,3668791 +FLAGS (\Deleted)
S: * 3480 FETCH (FLAGS (\Deleted) UID 3668787)
S: * 3481 FETCH (FLAGS (\Deleted) UID 3668788)
S: * 3482 FETCH (FLAGS (\Deleted) UID 3668790)
S: * 3483 FETCH (FLAGS (\Deleted) UID 3668791)
S: RUBY0037 OK UID STORE completed
C: RUBY0038 CLOSE
S: * NOOP
@str: "* NOOP\r\n"
@pos: 8
@lex_state: EXPR_BEG
@token.symbol: CRLF
@token.value: "\r\n"
[backtrace]
```
I did not find in RFC3501 if this was OK for Zimbra to do so, it seems not.

**Comment by c-leroy** [comment]
Ignoring these responses seems to be sufficient. I ignored 12 of these during a ```CLOSE``` request that lasted around 3-5 minutes, without side-effect, using this hack :
```ruby
module Net
  class IMAP
    class ResponseParser
      def parse(str)
        @str = str
        @pos = 0
        @lex_state = EXPR_BEG
        @token = nil
        if @str == "* NOOP\r\n"
          STDERR.puts "\e[31;1mGOT NOOP untagged response! Ignoring it.\e[0m"
          return 42
        end
        return response
      end
    end
  end
end
```

**Comment by c-leroy** [comment]
From Zimbra source code, it can send this during expunge, store and copy progress, every 15 seconds. For example:

https://github.com/Zimbra/zm-mailbox/blob/326aabc7b5e41de6fe1d1f0734be78c2c01609c2/store/src/java/com/zimbra/cs/imap/ImapHandler.java#L3502-L3507

I found no easy way to report this issue to Zimbra.
